### ISSUE TITLE
一键部署后会出现报错，无法使用

### ISSUE THREAD

**Issue by xiaolaji404** [walinejs/tcb-starter#16]
通过一键部署后，会出现如下报错
错误码: INVOKE_FUNCTION_FAILED
错误信息: Code: -1 ScfRequestId: c54e0727-6396-11ee-b3fe-52540043f6d7 Error: /var/user/node_modules/think-model-mysql2/node_modules/lru-cache/dist/cjs/index.js:359 #initializeTTLTracking() { ^ SyntaxError: Unexpected token '(' at wrapSafe (internal/modules/cjs/loader.js:1072:16) at Module._compile (internal/modules/cjs/loader.js:1122:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) at Module.load (internal/modules/cjs/loader.js:1002:32) at Function.Module._load (internal/modules/cjs/loader.js:901:14) at Module.require (internal/modules/cjs/loader.js:1044:19) at require (internal/modules/cjs/helpers.js:77:18) at Object.<anonymous> (/var/user/node_modules/think-model-mysql2/node_modules/lru-cache/dist/cjs/index-cjs.js:5:36) at Module._compile (internal/modules/cjs/loader.js:1158:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
无法使用

其次，腾讯云cloudbase更新新版控制台后，需要将页面设置为旧版控制台页面才会弹出快速部署选项弹窗，否则没有任何反应

**Comment by lizheming** [comment]
现在腾讯云部署应该用不起来了吧，腾讯云开发那边的 Node 版本还是 14，Waline 最低要求 16 了好像。

**Comment by xiaolaji404** [comment]
是的，最近因为vercel被墙的原因，想换回国内，尝试腾讯云发现不太行，我再看看其他平台，谢谢
